<a href="https://colab.research.google.com/github/Elmir22/Data-science-ML-models-/blob/main/00_tensorflow_fundamentais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TENSORFLOW

In [54]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [55]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [56]:
scalar.ndim

0

In [57]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [58]:
vector.ndim

1

In [59]:
matrix = tf.constant([[10,7],
                       [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [60]:
another_matrix = tf.constant([[5., 5.],
                              [5., 5.],
                              [5., 5.]], dtype = tf.float32)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[5., 5.],
       [5., 5.],
       [5., 5.]], dtype=float32)>

In [61]:
changeable_tensor = tf.Variable([5, 7])
unchangeable_tensor = tf.constant([5,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>)

In [62]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [63]:
changeable_tensor[0].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

In [64]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,3))
random_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [65]:
not_shuffled = tf.constant([[1,5],
                            [7,9],
                            [3,8]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [7, 9],
       [3, 8]], dtype=int32)>

In [66]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 8],
       [1, 5],
       [7, 9]], dtype=int32)>

In [67]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [7, 9],
       [3, 8]], dtype=int32)>

In [68]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [69]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [70]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [71]:
A = tf.constant(numpy_A, shape=(2,2,2,3))
A

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]], dtype=int32)>

In [72]:
zeros = tf.zeros([1,2,3,4,5,4])
zeros

<tf.Tensor: shape=(1, 2, 3, 4, 5, 4), dtype=float32, numpy=
array([[[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]

In [73]:
tf.rank(zeros)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [74]:
A.shape, A.ndim, tf.size(A), tf.rank(A)

(TensorShape([2, 2, 2, 3]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [75]:
def info_about_tensor(tensor):
  print("Data type of every element", tensor.dtype)
  print("Number of dimensions( Rank)", tf.rank(tensor))
  print("shape of tensor", tensor.shape)
  print("element along the 0 axis", tensor.shape[0])
  print("element along the last axis", tensor.shape[-1])
  print("total number of elements in our tensor", tf.size(tensor).numpy())

In [76]:
info_about_tensor(A)

Data type of every element <dtype: 'int32'>
Number of dimensions( Rank) tf.Tensor(4, shape=(), dtype=int32)
shape of tensor (2, 2, 2, 3)
element along the 0 axis 2
element along the last axis 3
total number of elements in our tensor 24


In [77]:
rank_2_tensor = tf.ones(shape=(2,3))
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [78]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [79]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [80]:
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [81]:
tensor = tf.constant([[1,5],
                      [7,9]])

In [82]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 50],
       [70, 90]], dtype=int32)>

In [83]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36,  50],
       [ 70, 116]], dtype=int32)>

In [84]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36,  50],
       [ 70, 116]], dtype=int32)>

In [85]:
X = tf.constant([[1,2,3],
                 [4,5,6]])
Y = tf.constant([[7,8,9],
                 [10,11,12]])
X,Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [86]:
Y = tf.transpose(Y)
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [87]:
tf.matmul(X,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [88]:
X@Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [89]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 10,  8],
       [11,  9, 12]], dtype=int32)>

In [90]:
tf.tensordot(X,Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [91]:
A = tf.constant([4,5])
A.dtype

tf.int32

In [92]:
A = tf.cast(A, dtype=tf.int16)

In [93]:
A.dtype

tf.int16

In [94]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape=[1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [95]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [96]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [97]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [98]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [99]:
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [100]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [101]:
matrix = tf.constant([[1,2],
                      [3,4]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [102]:
vector.shape

TensorShape([2])

In [103]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [104]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [108]:
A = tf.random.normal(shape = (5,300))
B = tf.random.normal(shape=(5,300))
A
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.65648675, -0.4130517 ,  0.33997506, ...,  1.5067012 ,
        -1.7496731 , -0.43718383],
       [-1.8551657 ,  0.77431184, -1.4388843 , ...,  1.297969  ,
         0.5977896 ,  1.4488887 ],
       [ 0.21232678, -1.5755495 ,  0.51170474, ..., -0.26204854,
         0.32715818, -0.9001915 ],
       [-2.728014  ,  0.5940714 ,  1.7169899 , ..., -0.01683606,
         0.20941465, -1.2812121 ],
       [ 0.09398963,  1.6349261 ,  1.7401077 , ..., -1.4561347 ,
         0.08837848, -0.06626268]], dtype=float32)>

In [110]:
B= tf.transpose(B)

In [111]:
A@B

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.1065745 , -22.983181  , -21.469358  , -13.420372  ,
         23.215508  ],
       [ -5.7122965 , -10.096172  ,  28.399124  , -12.702354  ,
        -18.722439  ],
       [-23.494946  ,  14.154114  ,   1.6560097 , -15.851512  ,
        -37.578484  ],
       [-21.221027  ,  33.993355  ,  14.518611  ,  -0.87672234,
          7.129793  ],
       [ 12.1591625 ,   9.512866  , -15.867203  ,  14.077565  ,
         26.852705  ]], dtype=float32)>

In [113]:
tf.tensordot(A,B, axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.1065745 , -22.983181  , -21.469358  , -13.420372  ,
         23.215508  ],
       [ -5.7122965 , -10.096172  ,  28.399124  , -12.702354  ,
        -18.722439  ],
       [-23.494946  ,  14.154114  ,   1.6560097 , -15.851512  ,
        -37.578484  ],
       [-21.221027  ,  33.993355  ,  14.518611  ,  -0.87672234,
          7.129793  ],
       [ 12.1591625 ,   9.512866  , -15.867203  ,  14.077565  ,
         26.852705  ]], dtype=float32)>

In [122]:
a = tf.random.uniform([224, 224, 3])
a

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.2046014 , 0.82478166, 0.81674874],
        [0.57813525, 0.72301936, 0.9893687 ],
        [0.33879173, 0.4470011 , 0.24898088],
        ...,
        [0.574314  , 0.6185826 , 0.4371407 ],
        [0.45086288, 0.673488  , 0.19694173],
        [0.7261505 , 0.4120711 , 0.11013401]],

       [[0.6134424 , 0.91840196, 0.6838045 ],
        [0.89331627, 0.67425346, 0.60953534],
        [0.36227953, 0.00483751, 0.22489178],
        ...,
        [0.84603393, 0.24309051, 0.18531716],
        [0.5195565 , 0.6304064 , 0.7182379 ],
        [0.22715592, 0.4978919 , 0.8341614 ]],

       [[0.15624535, 0.1719867 , 0.6037985 ],
        [0.86916864, 0.16423154, 0.9619628 ],
        [0.37755537, 0.9332715 , 0.8822973 ],
        ...,
        [0.82203424, 0.9220053 , 0.45980155],
        [0.66036093, 0.23616183, 0.37692404],
        [0.05016053, 0.35180223, 0.3742    ]],

       ...,

       [[0.08419359, 0.1039772 , 0.10614038],
        [0.76

In [126]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999887>

In [127]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=float32, numpy=8.34465e-07>

In [128]:
a = tf.random.uniform([1,224, 224, 3])
a

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.12780273, 0.86230123, 0.41563296],
         [0.10028672, 0.6078365 , 0.79052174],
         [0.06068337, 0.85674644, 0.72001266],
         ...,
         [0.42501688, 0.777889  , 0.7029644 ],
         [0.00265503, 0.4391595 , 0.89044964],
         [0.63493025, 0.87544703, 0.943701  ]],

        [[0.6613052 , 0.37710202, 0.51483595],
         [0.50989354, 0.9679649 , 0.45765674],
         [0.2590027 , 0.3557694 , 0.26365137],
         ...,
         [0.3261726 , 0.49975753, 0.1813755 ],
         [0.6064073 , 0.8051214 , 0.320701  ],
         [0.32923293, 0.5298729 , 0.39044487]],

        [[0.34140837, 0.47335994, 0.01272404],
         [0.47659898, 0.47509444, 0.8660991 ],
         [0.16929126, 0.09049737, 0.09263301],
         ...,
         [0.15332878, 0.2546159 , 0.9531114 ],
         [0.10869956, 0.5302429 , 0.8690088 ],
         [0.6384195 , 0.19085515, 0.35851824]],

        ...,

        [[0.62105274, 0.22180116, 

In [129]:
a_squeezed = tf.squeeze(a)
a_squeezed, a_squeezed.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.12780273, 0.86230123, 0.41563296],
         [0.10028672, 0.6078365 , 0.79052174],
         [0.06068337, 0.85674644, 0.72001266],
         ...,
         [0.42501688, 0.777889  , 0.7029644 ],
         [0.00265503, 0.4391595 , 0.89044964],
         [0.63493025, 0.87544703, 0.943701  ]],
 
        [[0.6613052 , 0.37710202, 0.51483595],
         [0.50989354, 0.9679649 , 0.45765674],
         [0.2590027 , 0.3557694 , 0.26365137],
         ...,
         [0.3261726 , 0.49975753, 0.1813755 ],
         [0.6064073 , 0.8051214 , 0.320701  ],
         [0.32923293, 0.5298729 , 0.39044487]],
 
        [[0.34140837, 0.47335994, 0.01272404],
         [0.47659898, 0.47509444, 0.8660991 ],
         [0.16929126, 0.09049737, 0.09263301],
         ...,
         [0.15332878, 0.2546159 , 0.9531114 ],
         [0.10869956, 0.5302429 , 0.8690088 ],
         [0.6384195 , 0.19085515, 0.35851824]],
 
        ...,
 
        [[0.62105274, 0.22180116

In [132]:
A = tf.constant([2, 20, 30, 3, 50])
tf.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=4>