<a href="https://colab.research.google.com/github/Elmir22/Data-science/blob/main/Employee_Attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [149]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import OrdinalEncoder

In [150]:
employee_attrition_test = pd.read_csv("/content/employee_attrition_test.csv")

In [151]:
employee_attrition_train = pd.read_csv("/content/employee_attrition_train.csv")

In [152]:
employee_attrition_test

Age     BusinessTravel  DailyRate              Department  \
0     NaN      Travel_Rarely      866.0                   Sales   
1    53.0      Travel_Rarely     1084.0  Research & Development   
2    24.0      Travel_Rarely      240.0         Human Resources   
3    45.0      Travel_Rarely     1339.0  Research & Development   
4    36.0      Travel_Rarely     1396.0  Research & Development   
..    ...                ...        ...                     ...   
436  33.0  Travel_Frequently      430.0                   Sales   
437  27.0         Non-Travel      210.0                   Sales   
438   NaN      Travel_Rarely     1157.0  Research & Development   
439  39.0      Travel_Rarely     1383.0         Human Resources   
440   NaN      Travel_Rarely      104.0  Research & Development   

     DistanceFromHome  Education   EducationField  EmployeeCount  \
0                 NaN          3          Medical              1   
1                13.0          2          Medical              1   
2                22.0          1  Human Resources              1   
3                 7.0          3    Life Sciences              1   
4                 NaN          2    Life Sciences              1   
..                ...        ...              ...            ...   
436               7.0          3          Medical              1   
437               1.0          1        Marketing              1   
438               2.0          4          Medical              1   
439               2.0          3    Life Sciences              1   
440               2.0          3    Life Sciences              1   

     EmployeeNumber  EnvironmentSatisfaction  ... RelationshipSatisfaction  \
0              1469                        4  ...                        4   
1               250                        4  ...                        3   
2              1714                        4  ...                        3   
3                86                        2  ...                        3   
4               304                        4  ...                        4   
..              ...                      ...  ...                      ...   
436            1477                        4  ...                        1   
437             449                        3  ...                        4   
438             440                        1  ...                        4   
439             909                        4  ...                        3   
440            1569                        1  ...                        4   

     StandardHours  StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
0               80                 0                  6                     4   
1               80                 2                  5                     3   
2               80                 1                  1                     2   
3               80                 1                 25                     2   
4               80                 0                 16                     3   
..             ...               ...                ...                   ...   
436             80                 2                  5                     2   
437             80                 1                  6                     0   
438             80                 0                  5                     4   
439             80                 2                 13                     2   
440             80                 1                  1                     2   

     WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                  3              5                   4   
1                  3              4                   2   
2                  3              1                   0   
3                  3              1                   0   
4                  4             13                  11   
..               ...            ...                 ...   
436                3              4                   3   
43

In [153]:
employee_attrition_train

Age Attrition     BusinessTravel  DailyRate              Department  \
0     50.0        No      Travel_Rarely     1126.0  Research & Development   
1     36.0        No      Travel_Rarely      216.0  Research & Development   
2     21.0       Yes      Travel_Rarely      337.0                   Sales   
3     50.0        No  Travel_Frequently     1246.0         Human Resources   
4     52.0        No      Travel_Rarely      994.0  Research & Development   
...    ...       ...                ...        ...                     ...   
1024   NaN        No      Travel_Rarely      750.0  Research & Development   
1025  41.0        No      Travel_Rarely      447.0  Research & Development   
1026  22.0       Yes  Travel_Frequently     1256.0  Research & Development   
1027  29.0        No      Travel_Rarely     1378.0  Research & Development   
1028  50.0        No      Travel_Rarely      264.0                   Sales   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                  1.0          2        Medical              1   
1                  6.0          2        Medical              1   
2                  7.0          1      Marketing              1   
3                  NaN          3        Medical              1   
4                  7.0          4  Life Sciences              1   
...                ...        ...            ...            ...   
1024              28.0          3  Life Sciences              1   
1025               NaN          3  Life Sciences              1   
1026               NaN          4  Life Sciences              1   
1027              13.0          2          Other              1   
1028               9.0          3      Marketing              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                997  ...                         3            80   
1                178  ...                         4            80   
2               1780  ...                         2            80   
3                644  ...                         3            80   
4               1118  ...                         4            80   
...              ...  ...                       ...           ...   
1024            1596  ...                         4            80   
1025            1814  ...                         1            80   
1026            1203  ...                         2            80   
1027            2053  ...                         1            80   
1028            1591  ...                         3            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    1                 32                      1   
1                    2                  7                      0   
2                    0                  1                      3   
3                    1                 32                      2   
4                    0                 18                      4   
...                ...                ...                    ...   
1024                 2                 10                      3   
1025                 0                 11                      3   
1026                 1                  1                      5   
1027                 1                 10                      2   
1028                 1                 27                      2   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  2               5                  4   
1                  3               3                  2   
2                  3               1                  0   
3                  3              32                  5   
4                  3               8                  6   
...              ...             ...                ...   
1024               2              10                  9   
1025               1               3                  2   
1026               3               0                  0   
1027               3         

In [154]:
employee_attrition_train.isna().sum()

Age                         136
Attrition                     0
BusinessTravel                5
DailyRate                    27
Department                    0
DistanceFromHome             95
Education                     0
EducationField                0
EmployeeCount                 0
EmployeeNumber                0
EnvironmentSatisfaction       0
Gender                        0
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction               0
MaritalStatus                 5
MonthlyIncome                 0
MonthlyRate                   0
NumCompaniesWorked            0
Over18                        0
OverTime                      0
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours                 0
StockOptionLevel              0
TotalWorkingYears             0
TrainingTimesLastYear         0
WorkLifeBalance               0
YearsAtC

In [155]:
employee_attrition_train.head(20)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   50.0        No      Travel_Rarely     1126.0  Research & Development   
1   36.0        No      Travel_Rarely      216.0  Research & Development   
2   21.0       Yes      Travel_Rarely      337.0                   Sales   
3   50.0        No  Travel_Frequently     1246.0         Human Resources   
4   52.0        No      Travel_Rarely      994.0  Research & Development   
5   33.0       Yes      Travel_Rarely     1277.0  Research & Development   
6   47.0        No      Travel_Rarely     1001.0  Research & Development   
7   22.0        No      Travel_Rarely     1230.0  Research & Development   
8    NaN       Yes      Travel_Rarely      890.0  Research & Development   
9   33.0        No         Non-Travel      530.0                   Sales   
10  40.0        No      Travel_Rarely      630.0                   Sales   
11  27.0        No  Travel_Frequently      793.0                   Sales   
12  40.0        No      Travel_Rarely      543.0  Research & Development   
13  55.0        No  Travel_Frequently     1091.0  Research & Development   
14  33.0       Yes      Travel_Rarely     1017.0  Research & Development   
15  37.0       Yes      Travel_Rarely      625.0                   Sales   
16  34.0        No      Travel_Rarely      511.0                   Sales   
17  46.0        No      Travel_Rarely      168.0                   Sales   
18  38.0        No      Travel_Rarely     1245.0                   Sales   
19  30.0        No      Travel_Rarely     1138.0  Research & Development   

    DistanceFromHome  Education    EducationField  EmployeeCount  \
0                1.0          2           Medical              1   
1                6.0          2           Medical              1   
2                7.0          1         Marketing              1   
3                NaN          3           Medical              1   
4                7.0          4     Life Sciences              1   
5               15.0          1           Medical              1   
6                4.0          3     Life Sciences              1   
7                1.0          2     Life Sciences              1   
8                2.0          4           Medical              1   
9               16.0          3     Life Sciences              1   
10               4.0          4         Marketing              1   
11               2.0          1     Life Sciences              1   
12               1.0          4     Life Sciences              1   
13               2.0          1     Life Sciences              1   
14              25.0          3           Medical              1   
15               1.0          4     Life Sciences              1   
16               NaN          2     Life Sciences              1   
17               4.0          2         Marketing              1   
18              14.0          3     Life Sciences              1   
19               6.0          3  Technical Degree              1   

    EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0              997  ...                         3            80   
1              178  ...                         4            80   
2             1780  ...                         2            80   
3              644  ...                         3            80   
4             1118  ...                         4            80   
5              582  ...                         4            80   
6             1827  ...                         3            80   
7              872  ...                         1            80   
8              828  ...                         4            80   
9             1681  ...                         3            80   
10             215  ...                         1            80   
11            1371  ...                         2            80   
12            2012  ...                         3            80   
13            1096  ...                  

In [156]:
employee_attrition_train = employee_attrition_train.drop(['EmployeeCount','EmployeeNumber','StandardHours'], axis= 1)

In [177]:
employee_attrition_train

Age Attrition     BusinessTravel  DailyRate              Department  \
0     50.0        No      Travel_Rarely     1126.0  Research & Development   
1     36.0        No      Travel_Rarely      216.0  Research & Development   
2     21.0       Yes      Travel_Rarely      337.0                   Sales   
3     50.0        No  Travel_Frequently     1246.0         Human Resources   
4     52.0        No      Travel_Rarely      994.0  Research & Development   
...    ...       ...                ...        ...                     ...   
1024   NaN        No      Travel_Rarely      750.0  Research & Development   
1025  41.0        No      Travel_Rarely      447.0  Research & Development   
1026  22.0       Yes  Travel_Frequently     1256.0  Research & Development   
1027  29.0        No      Travel_Rarely     1378.0  Research & Development   
1028  50.0        No      Travel_Rarely      264.0                   Sales   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                  1.0          2        Medical                        4   
1                  6.0          2        Medical                        2   
2                  7.0          1      Marketing                        2   
3                  NaN          3        Medical                        1   
4                  7.0          4  Life Sciences                        2   
...                ...        ...            ...                      ...   
1024              28.0          3  Life Sciences                        2   
1025               NaN          3  Life Sciences                        2   
1026               NaN          4  Life Sciences                        3   
1027              13.0          2          Other                        4   
1028               9.0          3      Marketing                        3   

     Gender  ...  PerformanceRating  RelationshipSatisfaction  \
0      Male  ...                  4                         3   
1      Male  ...                  4                         4   
2      Male  ...                  3                         2   
3      Male  ...                  3                         3   
4      Male  ...                  3                         4   
...     ...  ...                ...                       ...   
1024   Male  ...                  3                         4   
1025   Male  ...                  3                         1   
1026   Male  ...                  3                         2   
1027   Male  ...                  3                         1   
1028   Male  ...                  3                         3   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
0                    1                32                      1   
1                    2                 7                      0   
2                    0                 1                      3   
3                    1                32                      2   
4                    0                18                      4   
...                ...               ...                    ...   
1024                 2                10                      3   
1025                 0                11                      3   
1026                 1                 1                      5   
1027                 1                10                      2   
1028                 1                27                      2   

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                  2               5                   4   
1                  3               3                   2   
2                  3               1                   0   
3                  3              32                   5   
4                  3               8                   6   
...              ...             ...                 ...   
1024               2              10                   9   
1025               1               3                   2   
1026               

In [157]:
employee_attrition_train["Attrition"].value_counts()

No     853
Yes    176
Name: Attrition, dtype: int64

In [158]:
from sklearn.model_selection import train_test_split

X=employee_attrition_train.drop('Attrition', axis=1)
y= employee_attrition_train['Attrition'].copy()
encoded_y = OrdinalEncoder().fit_transform(np.array(y).reshape(-1, 1))

X_train,X_test,y_train,y_test=train_test_split(X,encoded_y,test_size=0.2, stratify= y)

In [159]:
cat_features = X_train.select_dtypes(exclude = [np.number]).columns
num_features = X_train.select_dtypes(include = [np.number]).columns
num_features

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [160]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


cat_pipeline= Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='Missing')),
    ('onehot', OneHotEncoder())
])

num_pipeline= Pipeline([(
    'imputer', SimpleImputer(strategy='median')
)])

transformer= ColumnTransformer([
    ('num',num_pipeline, num_features),
    ('cat',cat_pipeline, cat_features)
],remainder='passthrough')

In [161]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

column_names = transformer.get_feature_names_out()

X_train_transformed_df = pd.DataFrame(X_train_transformed, columns = column_names)
X_train_transformed_df
X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=column_names)


In [162]:
X_test_transformed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 54 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   num__Age                                206 non-null    float64
 1   num__DailyRate                          206 non-null    float64
 2   num__DistanceFromHome                   206 non-null    float64
 3   num__Education                          206 non-null    float64
 4   num__EnvironmentSatisfaction            206 non-null    float64
 5   num__HourlyRate                         206 non-null    float64
 6   num__JobInvolvement                     206 non-null    float64
 7   num__JobLevel                           206 non-null    float64
 8   num__JobSatisfaction                    206 non-null    float64
 9   num__MonthlyIncome                      206 non-null    float64
 10  num__MonthlyRate                        206 non-null    float6

In [163]:
X_test_transformed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 54 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   num__Age                                206 non-null    float64
 1   num__DailyRate                          206 non-null    float64
 2   num__DistanceFromHome                   206 non-null    float64
 3   num__Education                          206 non-null    float64
 4   num__EnvironmentSatisfaction            206 non-null    float64
 5   num__HourlyRate                         206 non-null    float64
 6   num__JobInvolvement                     206 non-null    float64
 7   num__JobLevel                           206 non-null    float64
 8   num__JobSatisfaction                    206 non-null    float64
 9   num__MonthlyIncome                      206 non-null    float64
 10  num__MonthlyRate                        206 non-null    float6

In [164]:
y_train

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [165]:
from sklearn.ensemble import RandomForestClassifier
reg = RandomForestClassifier()
reg.fit(X_train_transformed_df, y_train)

<ipython-input-165-4492864af5e9>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  reg.fit(X_train_transformed_df, y_train)


RandomForestClassifier()

In [166]:
reg.score(X_train_transformed_df,y_train)

1.0

In [167]:
reg.score(X_test_transformed_df,y_test)

0.8543689320388349

In [168]:

ordenc = OrdinalEncoder()
transformed_y= ordenc.fit_transform(np.array(y_test).reshape(-1, 1))
transformed_y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [169]:
y_test

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [170]:
ordenc = OrdinalEncoder()
transformed_X= ordenc.fit_transform(np.array(X_test_transformed_df).reshape(-1, 1))
transformed_X

array([[ 46.],
       [276.],
       [  2.],
       ...,
       [  1.],
       [  1.],
       [  0.]])

In [171]:
from sklearn.metrics import f1_score,recall_score,precision_score
preds = reg.predict(X_test_transformed_df)
preds

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [172]:
recall_score(preds,y_test)

0.8571428571428571

In [173]:
precision_score(preds,y_test)

0.17142857142857143

In [174]:
f1_score(preds,y_test)

0.2857142857142857

In [175]:
preds

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [176]:
y_test

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],