<a href="https://colab.research.google.com/github/Elmir22/Data-science/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
my_list =[1,2,3]
for i in my_list:
  print(i*2)

2
4
6


In [ ]:
a1*2

array([2, 4, 6])

In [ ]:
a2 = np.array([[1,2,3],
              [4,5,6]])

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.ndim

2

In [ ]:
random_array=np.random.randint(10,size=(2,3,4,5))

In [ ]:
random_array=[0]

In [ ]:
np.zeros(shape = (3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b1= np.random.randint (10,size = (2,3,3))
b2 = np.random.randint(10,size = (2,3))
b1

array([[[6, 9, 5],
        [7, 6, 2],
        [4, 3, 1]],

       [[1, 5, 1],
        [4, 2, 7],
        [0, 7, 5]]])

In [ ]:
b2

array([[4, 6, 6],
       [4, 3, 6]])

In [ ]:
b2.reshape(2,3,1)*b1

array([[[24, 36, 20],
        [42, 36, 12],
        [24, 18,  6]],

       [[ 4, 20,  4],
        [12,  6, 21],
        [ 0, 42, 30]]])

In [ ]:
b2.std()

1.2133516482134197

In [ ]:
a1.var()

0.6666666666666666

In [ ]:
c1 = np.random.randint(10,size=(2,3))
c2 = np.random.randint(10,size =(3,2))

In [ ]:
c1

array([[5, 8, 8],
       [7, 2, 8]])

In [ ]:
c2

array([[3, 1],
       [0, 8],
       [9, 5]])

In [ ]:
np.dot(c1,c2)

array([[ 87, 109],
       [ 93,  63]])

In [ ]:
c1.T.shape

(3, 2)

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4])
a1.shape

(4,)

In [ ]:
a1.size

4

In [ ]:
a2 = np.array([[1,2,3],[2,3,4]])
a2.shape

(2, 3)

In [ ]:
a3 = np.array([[1,2,3],
 [2,3,4,5],
  [98,1,2]])
a3.shape

<ipython-input-27-5cd0b917b999>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a3 = np.array([[1,2,3],


(3,)

In [ ]:
b1 = np.array([1,2,3])
b1.shape

(3,)

In [ ]:
b1.ndim

1

In [ ]:
b1.dtype

dtype('int64')

In [ ]:
b1.size

3

In [ ]:
b1.ndim

1

In [ ]:
a3.ndim

1

In [ ]:
import pandas as pd
import numpy as np

a1 = ([1,2,34,5])
df = pd.DataFrame(a1)
df

0
0   1
1   2
2  34
3   5

In [ ]:
a1 = np.random.randint(10,size=(2,5,4))
a1

array([[[0, 6, 8, 5],
        [1, 1, 5, 6],
        [5, 2, 3, 2],
        [1, 6, 0, 0],
        [4, 7, 2, 9]],

       [[8, 8, 3, 9],
        [4, 0, 7, 2],
        [4, 8, 9, 2],
        [5, 7, 6, 6],
        [8, 8, 4, 5]]])

In [ ]:
a1.ndim

3

In [ ]:
b1 = np.zeros((7,2,3))
b1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
c1 = np.arange(0,100,3)
c1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
c2 = np.random.randint(10,size=(7,2))
c2

array([[9, 5],
       [6, 8],
       [8, 9],
       [1, 0],
       [5, 1],
       [2, 8],
       [5, 7]])

In [ ]:
c3 = np.random.random((3,5))
c3

array([[0.43927905, 0.62880176, 0.04309384, 0.33705662, 0.57551427],
       [0.86704442, 0.46841746, 0.37391837, 0.46818372, 0.80059644],
       [0.66633278, 0.19070036, 0.96157394, 0.28494438, 0.17755048]])

In [ ]:
np.random.seed(42)
h1 = np.random.randint(10,size=(4,6))
h1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
h2 = np.random.randint(1,10,size=(3,7))
h2

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [ ]:
np.unique(h2)

array([1, 2, 3, 4, 5, 7, 9])

In [ ]:
h2[0]

array([9, 1, 3, 7, 4, 9, 3])

In [ ]:
h2[:2,:]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [ ]:
h2[:,[0,1,2]]

array([[9, 1, 3],
       [5, 3, 7],
       [4, 9, 2]])

In [ ]:
h2[:2,:2]

array([[9, 1],
       [5, 3]])

In [ ]:
h3 = np.random.randint(10,size=(3,5))
h3

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [ ]:
h4 = np.ones((3,5))
h4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
h5 = h3+h4
h5

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [ ]:
h6 = np.ones((5,3))
h6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
h7 = h4.T+h6
h7

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
h8 = np.ones((3,5))
h8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
h9 = h8-h7.T
h9

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [ ]:
h9 = h8*h7.T
h9

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
h10 = h5**2
h10

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [ ]:
np.square(h10)

array([[2.401e+03, 4.096e+03, 8.100e+01, 1.000e+00, 2.560e+02],
       [1.600e+01, 4.096e+03, 2.560e+02, 1.600e+01, 1.296e+03],
       [1.296e+03, 1.000e+04, 2.560e+02, 1.296e+03, 1.600e+01]])

In [ ]:
np.mean(h10)

30.333333333333332

In [ ]:
np.max(h10)

100.0

In [ ]:
np.min(h10)

1.0

In [ ]:
np.std(h10)

27.78168861358543

In [ ]:
np.var(h10)

771.8222222222224

In [ ]:
h10.reshape(3,5,1)

array([[[ 49.],
        [ 64.],
        [  9.],
        [  1.],
        [ 16.]],

       [[  4.],
        [ 64.],
        [ 16.],
        [  4.],
        [ 36.]],

       [[ 36.],
        [100.],
        [ 16.],
        [ 36.],
        [  4.]]])

In [ ]:
h10.T

array([[ 49.,   4.,  36.],
       [ 64.,  64., 100.],
       [  9.,  16.,  16.],
       [  1.,   4.,  36.],
       [ 16.,  36.,   4.]])

In [ ]:
g1 = np.random.randint(10,size=(3,3))
g1

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4]])

In [ ]:
g2 = np.random.randint(10,size=(3,2))
g2

array([[1, 4],
       [7, 9],
       [8, 8]])

In [ ]:
np.dot(g1,g2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

33,34 suallar hazirdi


In [ ]:
g3 = np.random.randint(10,size=(4,3))
g3

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2]])

In [ ]:
g4 = np.random.randint(10,size=(4,3))
g4


array([[2, 0, 4],
       [9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [ ]:
np.dot(g3,g4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

36CI SUAL HAZIRDI


In [ ]:
g3>g4

array([[False,  True,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [ ]:
g3>=g4

array([[False,  True,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [ ]:
g3>7

array([[False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
g3==g4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
g3.sort()
g3

array([[0, 6, 8],
       [0, 7, 8],
       [2, 7, 7],
       [0, 2, 7]])

In [ ]:
g3.argmax()

2

In [ ]:
g3.argmin()

0

In [ ]:
np.argsort(g3)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

basa dusmedim????

In [ ]:
evenly_spaced_array = np.linspace(1, 100, 10)
evenly_spaced_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

47 48 49 44 suallar qaldi
